#!/usr/bin/env bash
set -e errexit



if [[ ! -e "_config.yml" ]]; then
  toolsDir=$(dirname "${0}")
  wwwDir="${toolsDir}/../www.gothicarchive.org"

  if [[ ! -e "${wwwDir}" ]]; then
    echo "can't find ${wwwDir}" >&2
    exit 1
  fi
  
  cd "${wwwDir}"
fi

export JEKYLL_ENV=development

set -x
bundle exec jekyll serve --port 4420
